### ISSUE TITLE
The latest version, 4.4.1 in purpur1.20.1, a loop error occurs when the Mysql database is connected

### ISSUE THREAD

**Issue by qqwkt** [WiIIiam278/HuskHomes#444]
[20:38:22 WARN]: [HuskHomes] Plugin HuskHomes v4.4.1 generated an exception whilst handling plugin message
net.william278.huskhomes.libraries.adventure.key.InvalidKeyException: Non [a-z0-9_.-] character in value of Key[huskhomes:资源/4.4] at index
 0 ('资', bytes: [-24, -75, -124])
        at net.william278.huskhomes.libraries.adventure.key.KeyImpl.checkError(KeyImpl.java:58) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at net.william278.huskhomes.libraries.adventure.key.KeyImpl.<init>(KeyImpl.java:49) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at net.william278.huskhomes.libraries.adventure.key.Key.key(Key.java:137) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at net.william278.huskhomes.HuskHomes.getKey(HuskHomes.java:490) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at net.william278.huskhomes.network.Broker.getSubChannelId(Broker.java:154) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at net.william278.huskhomes.network.PluginMessageBroker.onReceive(PluginMessageBroker.java:66) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.onPluginMessageReceived(BukkitHuskHomes.java:492) ~[HuskHomes-Plugin-4.4.1.jar:?]
        at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.20.1-R0.1-SNAPSH
OT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3667) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1452) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2001]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by WiIIiam278** [comment]
You've set an illegal subnetwork key. Subnetwork keys must use English (latin; a-z) characters as this uses an adventure key.
There perhaps could be a bit more error handling here to make this obvious; but please replace the chinese characters in your cluster IDs.

**Comment by qqwkt** [comment]
> 

谢谢回复  嗯，在您的帮助下，我们已经修改好了
