### ISSUE TITLE
UNIQUE constraint failed: huskhomes_user_cooldowns.player_uuid

### ISSUE THREAD

**Issue by dentatar** [WiIIiam278/HuskHomes#497]
Plugin version: 4.5
Minecraft version: 1.20.1
Server version: Paper 194

Hello. I was using your plugin with default config for some time but recently decided to add cooldowns:
```
cooldowns:
  enabled: true
  cooldown_times:
    additional_home_slot: 6000
    make_home_public: 6000
    random_teleport: 600
    back_command: 600
    home_teleport: 600
    public_home_teleport: 600
    warp_teleport: 600
    spawn_teleport: 600
    send_teleport_request: 60
    accept_teleport_request: 60
```
Now every time someone is using commands i get sqlite error in the console:
```
[12:39:04 ERROR]: [HuskHomes] Failed to set a player's cooldown in the database
org.sqlite.SQLiteException: [SQLITE_CONSTRAINT_UNIQUE] A UNIQUE constraint failed (UNIQUE constraint failed: huskhomes_user_cooldowns.player_uuid)
	at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.core.DB.execute(DB.java:985) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.core.DB.executeUpdate(DB.java:1054) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeLargeUpdate$2(JDBC3PreparedStatement.java:119) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeLargeUpdate(JDBC3PreparedStatement.java:118) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeUpdate(JDBC3PreparedStatement.java:100) ~[sqlite-jdbc-3.42.0.0.jar:?]
	at net.william278.huskhomes.database.SqLiteDatabase.setCooldown(SqLiteDatabase.java:394) ~[HuskHomes-Plugin-4.5.jar:?]
	at net.william278.huskhomes.util.TransactionResolver.performTransaction(TransactionResolver.java:132) ~[HuskHomes-Plugin-4.5.jar:?]
	at net.william278.huskhomes.teleport.Teleport.lambda$performTransactions$7(Teleport.java:199) ~[HuskHomes-Plugin-4.5.jar:?]
	at java.lang.Iterable.forEach(Unknown Source) ~[?:?]
	at net.william278.huskhomes.teleport.Teleport.performTransactions(Teleport.java:199) ~[HuskHomes-Plugin-4.5.jar:?]
	at net.william278.huskhomes.teleport.Teleport.lambda$execute$4(Teleport.java:146) ~[HuskHomes-Plugin-4.5.jar:?]
	at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Plugin-4.5.jar:?]
	at net.william278.huskhomes.event.EventDispatcher.lambda$fireEvent$0(EventDispatcher.java:53) ~[HuskHomes-Plugin-4.5.jar:?]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.1.jar:git-Paper-194]
	at org.bukkit.craftbukkit.v1_20_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.1.jar:git-Paper-194]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.1.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[?:?]
	at java.lang.Thread.run(Unknown Source) ~[?:?]
```
Cooldowns are not working for player when error occur, but not all players are affected for some reason.

**Comment by WiIIiam278** [comment]
Already fixed in https://github.com/WiIIiam278/HuskHomes/commit/c5a85436be516cc018290d31ad7a484fda5d884b

You probably upgraded to one of the versions which had that constraint still in it as the schema when it made it
