### ISSUE TITLE
player can't teleport warp with messages 'error_already_teleporting'

### ISSUE THREAD

**Issue by Ecilpse** [WiIIiam278/HuskHomes#549]
```
[23:23:09] [Craft Scheduler Thread - 6951 - HuskHomes/ERROR]: [HuskHomes] Failed to clear the current teleport of EX999
java.sql.SQLIntegrityConstraintViolationException: Duplicate entry 'ef7d894b-ffa9-449e-b6a0-c0a31b619d2e' for key 'huskhomes_teleports.PRIMARY'
    at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:118) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.ServerPreparedStatement.serverExecute(ServerPreparedStatement.java:555) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.ServerPreparedStatement.executeInternal(ServerPreparedStatement.java:339) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1061) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdateInternal(ClientPreparedStatement.java:1009) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeLargeUpdate(ClientPreparedStatement.java:1320) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at com.mysql.cj.jdbc.ClientPreparedStatement.executeUpdate(ClientPreparedStatement.java:994) ~[mysql-connector-j-8.1.0.jar:8.1.0]
    at net.william278.huskhomes.libraries.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HuskHomes-Plugin-4.4.5.jar:?]
    at net.william278.huskhomes.libraries.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HuskHomes-Plugin-4.4.5.jar:?]
    at net.william278.huskhomes.database.MySqlDatabase.setCurrentTeleport(MySqlDatabase.java:782) ~[HuskHomes-Plugin-4.4.5.jar:?]
    at net.william278.huskhomes.teleport.Teleport.lambda$execute$4(Teleport.java:163) ~[HuskHomes-Plugin-4.4.5.jar:?]
    at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Plugin-4.4.5.jar:?]
    at net.william278.huskhomes.event.EventDispatcher.lambda$fireEvent$0(EventDispatcher.java:53) ~[HuskHomes-Plugin-4.4.5.jar:?]
    at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftTask.run(CraftTask.java:101) ~[paper-1.20.2.jar:git-Paper-318]
    at org.bukkit.craftbukkit.v1_20_R2.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[paper-1.20.2.jar:git-Paper-318]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[paper-1.20.2.jar:?]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
    at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by WiIIiam278** [comment]
Should be fixed by a change made in HuskHomes 4.6
