### ISSUE TITLE
Plugin is unable to connect to the MySQL database

### ISSUE THREAD

**Issue by xiaoluofa** [WiIIiam278/HuskHomes#569]
This error occurred when I upgraded my huskhome to 4.6.
My database used to work properly.
I returned the version of huskhome and the database worked properly.

**Comment by xiaoluofa** [comment]
I don't know what I should modify to use the new version of huskhome

**Comment by WiIIiam278** [comment]
Please provide startup logs for when you upgraded to HuskHomes 4.6

**Comment by xiaoluofa** [comment]
[14:04:10 ERROR]: Error occurred while enabling HuskHomes v4.6 (Is it up to date?)
java.lang.IllegalStateException: Failed to initialize plugin config & locale files
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:147) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.onEnable(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.RuntimeException: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{type=MYSQL, credentials={host=localhost, port=3306, database=huskhomes, username=root, password=112192, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}, pool_options={size=12, idle=12, lifetime=1800000, keep_alive=30000, timeout=20000}, table_names={PLAYER_DATA=huskhomes_users, PLAYER_COOLDOWNS_DATA=huskhomes_user_cooldowns, POSITION_DATA=huskhomes_position_data, SAVED_POSITION_DATA=huskhomes_saved_positions, HOME_DATA=huskhomes_homes, WARP_DATA=huskhomes_warps, TELEPORT_DATA=huskhomes_teleports}}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings net.william278.huskhomes.config.Settings.database' failed.
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.jar:?]
        ... 13 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{type=MYSQL, credentials={host=localhost, port=3306, database=huskhomes, username=root, password=112192, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}, pool_options={size=12, idle=12, lifetime=1800000, keep_alive=30000, timeout=20000}, table_names={PLAYER_DATA=huskhomes_users, PLAYER_COOLDOWNS_DATA=huskhomes_user_cooldowns, POSITION_DATA=huskhomes_position_data, SAVED_POSITION_DATA=huskhomes_saved_positions, HOME_DATA=huskhomes_homes, WARP_DATA=huskhomes_warps, TELEPORT_DATA=huskhomes_teleports}}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings net.william278.huskhomes.config.Settings.database' failed.
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:92) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.jar:?]
        ... 13 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{host=localhost, port=3306, database=huskhomes, username=root, password=112192, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings$DatabaseCredentials net.william278.huskhomes.config.Settings$DatabaseSettings.credentials' failed.
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:92) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.jar:?]
        ... 13 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '112192' with type 'class java.lang.Integer' for field 'private java.lang.String net.william278.huskhomes.config.Settings$DatabaseSettings$DatabaseCredentials.password' failed.
The type of the object to be deserialized does not match the type the deserializer expects.
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:89) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.jar:?]
        ... 13 more
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        at net.william278.huskhomes.libraries.configlib.Serializers$StringSerializer.deserialize(Serializers.java:163) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.jar:?]
        ... 13 more
[14:04:10 INFO]: [HuskHomes] Disabling HuskHomes v4.6
[14:04:12 ERROR]: Failed to request yggdrasil public key
com.mojang.authlib.exceptions.MinecraftClientException: Failed to read from https://api.minecraftservices.com/publickeys due to Connect timed out
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:108) ~[authlib-6.0.52.jar:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.get(MinecraftClient.java:57) ~[authlib-6.0.52.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo.fetch(YggdrasilServicesKeyInfo.java:114) ~[authlib-6.0.52.jar:?]
        at com.mojang.authlib.yggdrasil.YggdrasilServicesKeyInfo$1.run(YggdrasilServicesKeyInfo.java:89) ~[authlib-6.0.52.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.net.SocketTimeoutException: Connect timed out
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:551) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:602) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[?:?]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:178) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:533) ~[?:?]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:638) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[?:?]
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1287) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[?:?]
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1665) ~[?:?]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1589) ~[?:?]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:529) ~[?:?]
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:308) ~[?:?]
        at com.mojang.authlib.minecraft.client.MinecraftClient.readInputStream(MinecraftClient.java:84) ~[authlib-6.0.52.jar:?]
        ... 9 more

**Comment by WiIIiam278** [comment]
You needed to regenerate your config file (delete, then let the plugin recreate). Please do this.
