### ISSUE TITLE
error I deleted the configuration file and configured mysql correctly, but it still reported an error. My other plug-ins that connect to mysql are working normally.

### ISSUE THREAD

**Issue by xiaoluofa** [WiIIiam278/HuskHomes#571]
[11:10:30 ERROR]: Error occurred while enabling HuskHomes v4.6.1-7ee4bae (Is it up to date?)
java.lang.IllegalStateException: Failed to initialize plugin config & locale files
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:147) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.onEnable(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[luminol-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:646) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:557) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:713) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:458) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:312) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1217) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:346) ~[luminol-1.20.4.jar:git-Luminol-"58d264f"]
        at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.RuntimeException: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{type=MYSQL, credentials={host=localhost, port=3306, database=huskhomes, username=root, password=112192, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}, pool_options={size=12, idle=12, lifetime=1800000, keep_alive=30000, timeout=20000}, table_names={PLAYER_DATA=huskhomes_users, PLAYER_COOLDOWNS_DATA=huskhomes_user_cooldowns, POSITION_DATA=huskhomes_position_data, SAVED_POSITION_DATA=huskhomes_saved_positions, HOME_DATA=huskhomes_homes, WARP_DATA=huskhomes_warps, TELEPORT_DATA=huskhomes_teleports}}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings net.william278.huskhomes.config.Settings.database' failed.
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        ... 13 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{type=MYSQL, credentials={host=localhost, port=3306, database=huskhomes, username=root, password=112192, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}, pool_options={size=12, idle=12, lifetime=1800000, keep_alive=30000, timeout=20000}, table_names={PLAYER_DATA=huskhomes_users, PLAYER_COOLDOWNS_DATA=huskhomes_user_cooldowns, POSITION_DATA=huskhomes_position_data, SAVED_POSITION_DATA=huskhomes_saved_positions, HOME_DATA=huskhomes_homes, WARP_DATA=huskhomes_warps, TELEPORT_DATA=huskhomes_teleports}}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings net.william278.huskhomes.config.Settings.database' failed.
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:92) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        ... 13 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{host=localhost, port=3306, database=huskhomes, username=root, password=112192, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings$DatabaseCredentials net.william278.huskhomes.config.Settings$DatabaseSettings.credentials' failed.
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:92) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        ... 13 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '112192' with type 'class java.lang.Integer' for field 'private java.lang.String net.william278.huskhomes.config.Settings$DatabaseSettings$DatabaseCredentials.password' failed.
The type of the object to be deserialized does not match the type the deserializer expects.
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:89) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        ... 13 more
Caused by: java.lang.ClassCastException: class java.lang.Integer cannot be cast to class java.lang.String (java.lang.Integer and java.lang.String are in module java.base of loader 'bootstrap')
        at net.william278.huskhomes.libraries.configlib.Serializers$StringSerializer.deserialize(Serializers.java:163) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:84) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:31) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:9) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.BukkitHuskHomes.lambda$onEnable$0(BukkitHuskHomes.java:132) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Paper-4.6.1-7ee4bae.jar:?]
        ... 13 more

**Comment by WiIIiam278** [comment]
Please open a ticket or ask on the Discord for support questions -- it's a far better place than GitHub issues (which are for tracking plugin issues). In this case you've specified a numeric password in a string yaml field. Surround your password with single-quotes to fix this.
