### ISSUE TITLE
Error executing teleport: ILLEGAL_TARGET_COORDINATES

### ISSUE THREAD

**Issue by MSCMDD** [WiIIiam278/HuskHomes#641]
[22:12:56 WARN]: [HuskHomes] Plugin HuskHomes v4.6.3 generated an exception while executing task 4060
java.lang.RuntimeException: net.william278.huskhomes.teleport.TeleportationException: Error executing teleport: ILLEGAL_TARGET_COORDINATES
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[HuskHomes-Paper-4.6.3.jar:?]
        at net.william278.huskhomes.event.EventDispatcher.lambda$fireEvent$0(EventDispatcher.java:55) ~[HuskHomes-Paper-4.6.3.jar:?]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftTask.run(CraftTask.java:93) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at org.bukkit.craftbukkit.v1_20_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.20.4.jar:git-Leaves-"e7c14b8"]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.20.4.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: net.william278.huskhomes.teleport.TeleportationException: Error executing teleport: ILLEGAL_TARGET_COORDINATES
        at net.william278.huskhomes.user.BukkitUser.teleportLocally(BukkitUser.java:120) ~[HuskHomes-Paper-4.6.3.jar:?]
        at net.william278.huskhomes.teleport.Teleport.lambda$executeLocal$3(Teleport.java:128) ~[HuskHomes-Paper-4.6.3.jar:?]
        at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.6.3.jar:?]
        ... 7 more

**Comment by WiIIiam278** [comment]
Hello, this error is thrown as a safety mechanism when a user tries to teleport outside the world.
If you're constantly getting this error, please get in touch on Discord with more information so we can help you debug it :)
