### ISSUE TITLE
Huskhomes 4.7 for Fabric 1.20.1 failed to start Minecraft server

### ISSUE THREAD

**Issue by KiwiFlavoredApollo** [WiIIiam278/HuskHomes#670]
Downloaded the mod from [Modrinth](https://modrinth.com/plugin/huskhomes/version/cA0nmJeA)

[2024-08-08-3.log](https://github.com/user-attachments/files/16539244/2024-08-08-3.log)

```
[15:46:54] [main/ERROR]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'huskhomes'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:388) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:386) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:64) ~[fabric-loader-0.15.11.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.15.11.jar:?]
	at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) ~[fabric-server-mc.1.20.1-loader.0.15.11-launcher.1.0.1.jar:1.0.1]
Caused by: java.lang.IllegalStateException: Failed to initialize plugin config & locale files
	at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:147) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.onInitializeServer(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: java.lang.RuntimeException: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{type=SQLITE, mysql={credentials={host=localhost, port=3306, database=HuskHomes, username=root, password=pa55w0rd, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}, connection_pool={size=12, idle=12, lifetime=1800000, keepalive=30000, timeout=20000}}, table_names={saved_position_data=huskhomes_saved_positions, player_data=huskhomes_users, teleport_data=huskhomes_teleports, warp_data=huskhomes_warps, home_data=huskhomes_homes, position_data=huskhomes_position_data}}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings net.william278.huskhomes.config.Settings.database' failed.
	at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.onInitializeServer(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{type=SQLITE, mysql={credentials={host=localhost, port=3306, database=HuskHomes, username=root, password=pa55w0rd, parameters=?autoReconnect=true&useSSL=false&useUnicode=true&characterEncoding=UTF-8}, connection_pool={size=12, idle=12, lifetime=1800000, keepalive=30000, timeout=20000}}, table_names={saved_position_data=huskhomes_saved_positions, player_data=huskhomes_users, teleport_data=huskhomes_teleports, warp_data=huskhomes_warps, home_data=huskhomes_homes, position_data=huskhomes_position_data}}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$DatabaseSettings net.william278.huskhomes.config.Settings.database' failed.
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:116) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.lambda$onInitializeServer$1(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.onInitializeServer(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{saved_position_data=huskhomes_saved_positions, player_data=huskhomes_users, teleport_data=huskhomes_teleports, warp_data=huskhomes_warps, home_data=huskhomes_homes, position_data=huskhomes_position_data}' with type 'class java.util.LinkedHashMap' for field 'private java.util.Map net.william278.huskhomes.config.Settings$DatabaseSettings.tableNames' failed.
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:116) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:108) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.lambda$onInitializeServer$1(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.onInitializeServer(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Enum class Table does not contain enum 'saved_position_data'. Valid values are: [PLAYER_DATA, PLAYER_COOLDOWNS_DATA, POSITION_DATA, SAVED_POSITION_DATA, HOME_DATA, WARP_DATA, TELEPORT_DATA]
	at net.william278.huskhomes.libraries.configlib.Serializers$EnumSerializer.deserialize(Serializers.java:355) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.Serializers$EnumSerializer.deserialize(Serializers.java:335) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.Serializers$MapSerializer.deserialize(Serializers.java:475) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.Serializers$MapSerializer.deserialize(Serializers.java:432) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:108) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:108) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.lambda$onInitializeServer$1(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.HuskHomes.initialize(HuskHomes.java:145) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.william278.huskhomes.FabricHuskHomes.onInitializeServer(FabricHuskHomes.java:136) ~[HuskHomes-Fabric-4.7+mc.1.20.1.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.11.jar:?]
	... 7 more
```

**Comment by WiIIiam278** [comment]
Please regenerate your config.yml file
