### ISSUE TITLE
SQLITE_BUSY still causing data loss when using SQLite for storage

### ISSUE THREAD

**Issue by roggy666** [WiIIiam278/HuskHomes#688]
My players told me that their homes are not properly saving
[08:03:13] [Craft Scheduler Thread - 923 - HuskHomes/ERROR]: [HuskHomes] Failed to set the offline position of CoolMedusa37602
org.sqlite.SQLiteException: [SQLITE_BUSY] The database file is locked (cannot commit transaction - SQL statements in progress)
	at org.sqlite.core.DB.newSQLException(DB.java:1179) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.newSQLException(DB.java:1190) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.throwex(DB.java:1150) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.ensureAutocommit(DB.java:1255) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.lambda$ensureAutoCommit$2(DB.java:1226) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.SafeStmtPtr.safeRunConsume(SafeStmtPtr.java:142) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.lambda$ensureAutoCommit$3(DB.java:1225) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.SafeStmtPtr.safeRunConsume(SafeStmtPtr.java:142) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.ensureAutoCommit(DB.java:1223) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.core.DB.execute(DB.java:977) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.lambda$executeQuery$1(JDBC3PreparedStatement.java:92) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3Statement.withConnectionTimeout(JDBC3Statement.java:454) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at org.sqlite.jdbc3.JDBC3PreparedStatement.executeQuery(JDBC3PreparedStatement.java:87) ~[sqlite-jdbc-3.46.0.0.jar:?]
	at HuskHomes-Paper-4.7 (1).jar/net.william278.huskhomes.database.SqLiteDatabase.setOfflinePosition(SqLiteDatabase.java:890) ~[HuskHomes-Paper-4.7 (1).jar:?]
	at HuskHomes-Paper-4.7 (1).jar/net.william278.huskhomes.listener.EventListener.lambda$handlePlayerLeave$7(EventListener.java:106) ~[HuskHomes-Paper-4.7 (1).jar:?]
	at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:86) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[purpur-1.21.1.jar:1.21.1-2305-fdfc12e]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[purpur-1.21.1.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

**Comment by WiIIiam278** [comment]
Should be fixed by #708
