### ISSUE TITLE
Teleport failed when using command like /tp player x y z 0 0

### ISSUE THREAD

**Issue by cygbs** [WiIIiam278/HuskHomes#738]
I'm try to teleport with specify orientation, so I used '/tp player 0 0 0 0 0', console output some warns and HuskHomes says this player teleported, but this player on original location.

```
[00:02:09 INFO]: Ygbs issued server command: /tp Ygbs 0 0 0 0 0
[00:02:09 WARN]: [HuskHomes] Plugin HuskHomes v4.8.3 generated an exception while executing task 6321
java.lang.RuntimeException: net.william278.huskhomes.teleport.TeleportationException: Error executing teleport: WORLD_NOT_FOUND
        at HuskHomes-Paper-4.8.3.jar/net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:45) ~[HuskHomes-Paper-4.8.3.jar:?]
        at HuskHomes-Paper-4.8.3.jar/net.william278.huskhomes.event.EventDispatcher.lambda$fireEvent$0(EventDispatcher.java:55) ~[HuskHomes-Paper-4.8.3.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaves-1.21.3.jar:1.21.3-83-aeeef22]
        at org.bukkit.craftbukkit.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57) ~[leaves-1.21.3.jar:1.21.3-83-aeeef22]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[leaves-1.21.3.jar:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: net.william278.huskhomes.teleport.TeleportationException: Error executing teleport: WORLD_NOT_FOUND
        at HuskHomes-Paper-4.8.3.jar/net.william278.huskhomes.user.BukkitUser.teleportLocally(BukkitUser.java:114) ~[HuskHomes-Paper-4.8.3.jar:?]
        at HuskHomes-Paper-4.8.3.jar/net.william278.huskhomes.teleport.Teleport.lambda$executeLocal$5(Teleport.java:129) ~[HuskHomes-Paper-4.8.3.jar:?]
        at HuskHomes-Paper-4.8.3.jar/net.william278.huskhomes.libraries.desertwell.util.ThrowingConsumer.accept(ThrowingConsumer.java:43) ~[HuskHomes-Paper-4.8.3.jar:?]
        ... 7 more
> 
```

When I try using '/minecraft:tp Ygbs 0 0 0 0 0', it works, and player teleported (vanilla output form chat). So I think this is a HuskHomes's issue.

I want know why HuskHomes can not teleport player with specify orientation, and can this issue be fixed?

**Comment by WiIIiam278** [comment]
`/tp (player) (x y z) (world) (server) (yaw) (pitch)` should work?

**Comment by cygbs** [comment]
I tried using '/tp Ygbs 0 0 0 world 0 0' and found no issues. Thank you for your response, and can you fix it to prompt the player after using the wrong command instead of outputting a warning on the terminal?

**Comment by WiIIiam278** [comment]
umm can look at that
