### ISSUE TITLE
[BUG]The plugin cannot be loaded

### ISSUE THREAD

**Issue by XXJNOTFOUND** [WiIIiam278/HuskHomes#739]
as the title
This is the log output by the server
```
[00:20:43] [Server thread/INFO]: [HuskHomes] Loading server plugin HuskHomes v4.8.4-43109ec
[00:20:43] [Server thread/ERROR]: [HuskHomes] An error occurred whilst loading HuskHomes
net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '{region={min=500, max=5000}, distribution_mean=0.75, distribution_standard_deviation=2.0, restricted_worlds=[world_nether, world_the_end], cross_server=false, random_target_servers=[server-01, server-02]}' with type 'class java.util.LinkedHashMap' for field 'private net.william278.huskhomes.config.Settings$RtpSettings net.william278.huskhomes.config.Settings.rtp' failed.
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:116) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.load(YamlConfigurationStore.java:132) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.YamlConfigurationStore.update(YamlConfigurationStore.java:161) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.YamlConfigurations.update(YamlConfigurations.java:219) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.config.ConfigProvider.loadSettings(ConfigProvider.java:72) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.config.ConfigProvider.loadConfigs(ConfigProvider.java:46) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.HuskHomes.load(HuskHomes.java:70) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.BukkitHuskHomes.onLoad(BukkitHuskHomes.java:128) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:59) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at io.papermc.paper.plugin.storage.ServerPluginProviderStorage.processProvided(ServerPluginProviderStorage.java:18) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:564) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:337) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1216) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[leaf-1.21.1.jar:1.21.1-DEV-890793b]
	at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: net.william278.huskhomes.libraries.configlib.ConfigurationException: Deserialization of value '[server-01, server-02]' with type 'class java.util.ArrayList' for field 'private java.util.Map net.william278.huskhomes.config.Settings$RtpSettings.randomTargetServers' failed.
The type of the object to be deserialized does not match the type the deserializer expects.
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:113) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:108) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	... 19 more
Caused by: java.lang.ClassCastException: class java.util.ArrayList cannot be cast to class java.util.Map (java.util.ArrayList and java.util.Map are in module java.base of loader 'bootstrap')
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.Serializers$MapSerializer.deserialize(Serializers.java:432) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:108) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserializeConfigurationElements(TypeSerializer.java:146) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:15) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.ConfigurationSerializer.deserialize(ConfigurationSerializer.java:8) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	at HuskHomes-Paper-4.8.4-43109ec.jar/net.william278.huskhomes.libraries.configlib.TypeSerializer.deserialize(TypeSerializer.java:108) ~[HuskHomes-Paper-4.8.4-43109ec.jar:?]
	... 19 more
[00:20:43] [Server thread/INFO]: [HuskHomes] Disabling HuskHomes...
```

**Comment by XXJNOTFOUND** [comment]
I have tried both the official version and the beta version, and this error occurs

**Comment by WiIIiam278** [comment]
You havent regenerated your config file. Please check the update notes for details.
